field: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
fieldLayouts:
  9469d0bf-7979-42d2-aeb1-fbec3dd732e1:
    tabs:
      -
        elements:
          -
            fieldUid: 9a1afb30-f8c5-411a-bd8c-5bfd145b9e2c # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 59bec1aa-61be-4c85-bc31-ed5ee9871741 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 75979b57-72e1-4ff5-95b3-09762482b592 # Top Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a4c9746-d29b-4455-a732-a8d146232bbf # Person Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54a22aed-d769-4392-9448-0d9089c79b60 # Random Story
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0120ff0-936f-416b-9bfc-168bf2408950 # Background Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a287f7b-dd3a-4cdb-8b98-48f1e2ee58c1 # Module ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0a287f7b-dd3a-4cdb-8b98-48f1e2ee58c1: # Module ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: moduleId
    instructions: ''
    name: 'Module ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2a4c9746-d29b-4455-a732-a8d146232bbf: # Person Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: personImage
    instructions: ''
    name: 'Person Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9a1afb30-f8c5-411a-bd8c-5bfd145b9e2c: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  54a22aed-d769-4392-9448-0d9089c79b60: # Random Story
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: randomStory
    instructions: ''
    name: 'Random Story'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 963478cf-da01-4a9a-8ded-a13a53242ff9 # Character
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d072491e-63c4-4de7-8310-8164667fcf72 # Top Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 63ffb21f-885c-4cf6-a84c-22a8792f3dc3 # Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - aa22c616-dfd3-47d0-8774-df6510630fd7 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 686cdb01-cbca-45be-8913-b76e21a51b03 # Btn Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_5_randomstory}}'
      fieldLayout: row
      maxRows: '1'
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  59bec1aa-61be-4c85-bc31-ed5ee9871741: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  75979b57-72e1-4ff5-95b3-09762482b592: # Top Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: topText
    instructions: ''
    name: 'Top Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a0120ff0-936f-416b-9bfc-168bf2408950: # Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: beforeSleeping
name: 'Before Sleeping'
sortOrder: 2
