field: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
fieldLayouts:
  da8ac54a-59a2-4e2d-9927-e5eb82b265f2:
    tabs:
      -
        elements:
          -
            fieldUid: 9680b49c-b04e-4c96-8900-6a892993caa8 # Top Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9cb342de-e6d1-4d7f-b683-712e4d386889 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3d8733a9-1971-424a-9db6-c88c4420f775 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d024166d-eb74-487d-bea1-85dde5252324 # Slider
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4020c52a-1f9d-4527-92c4-cdda2f754de6 # Module ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3d8733a9-1971-424a-9db6-c88c4420f775: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9cb342de-e6d1-4d7f-b683-712e4d386889: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4020c52a-1f9d-4527-92c4-cdda2f754de6: # Module ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: moduleId
    instructions: ''
    name: 'Module ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9680b49c-b04e-4c96-8900-6a892993caa8: # Top Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: topTitle
    instructions: ''
    name: 'Top Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d024166d-eb74-487d-bea1-85dde5252324: # Slider
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slider
    instructions: ''
    name: Slider
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 68a6525a-1a83-400d-8430-3627525e49b9 # Phone Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_6_slider}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: catalog
name: Catalog
sortOrder: 3
