field: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
fieldLayouts:
  92e27720-98bc-48e4-aa87-058eddc1050f:
    tabs:
      -
        elements:
          -
            fieldUid: a157a8a1-b16f-4f2d-92c9-75219eb257f6 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 07d734b2-d967-4f6e-85e2-962785788469 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 644dd979-58cd-4fcf-911c-ad9bd2ffc3d0 # Store
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e941803a-0478-42db-a0cd-8c2fada3f059 # Phone Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 680bd3a1-016d-4e2b-b820-9267a206301a # Module ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  07d734b2-d967-4f6e-85e2-962785788469: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  644dd979-58cd-4fcf-911c-ad9bd2ffc3d0: # Store
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: store
    instructions: ''
    name: Store
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - b567ebb8-3604-4460-94e9-0e39ff0c6be8 # Destination
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c3184613-b616-476c-8e04-3d5a13f5f518 # Image Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_store}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  680bd3a1-016d-4e2b-b820-9267a206301a: # Module ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: moduleId
    instructions: ''
    name: 'Module ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a157a8a1-b16f-4f2d-92c9-75219eb257f6: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e941803a-0478-42db-a0cd-8c2fada3f059: # Phone Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: phoneImage
    instructions: ''
    name: 'Phone Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: joinUs
name: 'Join Us'
sortOrder: 5
