field: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
fieldLayouts:
  47b1e4e9-907c-49cf-a4cd-e4cbf7080830:
    tabs:
      -
        elements:
          -
            fieldUid: 962a5026-118c-4d2c-91f8-a25bf0881172 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7a43c953-3dd4-40d5-bbe8-498e7411a32c # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: dc4aeb13-05e2-4e9d-98d1-a1a81f577136 # Statistic
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 1305912f-e7bd-4297-b074-b9c45da795db # Module ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7a43c953-3dd4-40d5-bbe8-498e7411a32c: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  962a5026-118c-4d2c-91f8-a25bf0881172: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 16e3947f-f17f-4564-88b1-5bbfd87258f5 # Phone Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2d46993a-c728-4402-a5b2-515f7b24dcf3 # Character Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5df73bb3-fa30-415f-aed6-330f010f0842 # Statistics
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_images}}'
      fieldLayout: row
      maxRows: '1'
      minRows: '1'
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  1305912f-e7bd-4297-b074-b9c45da795db: # Module ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: moduleId
    instructions: ''
    name: 'Module ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dc4aeb13-05e2-4e9d-98d1-a1a81f577136: # Statistic
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: statistic
    instructions: ''
    name: Statistic
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 7322d969-ae2d-41ba-ac69-fe6edcb9bfdb # Icon
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6d528fe1-e1c1-4f21-92dc-d225ee195535 # Number
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6d369b4f-867a-4924-81b3-129f5bf18721 # Description
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_statistic}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: statistics
name: Statistics
sortOrder: 1
