field: 5df73bb3-fa30-415f-aed6-330f010f0842 # Statistics
fieldLayouts:
  3c3503e7-1695-4540-a41a-6b5eb2ae57eb:
    tabs:
      -
        elements:
          -
            fieldUid: 32aa8ee0-7612-4171-890d-39e6eca303f3 # Icon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 31937085-7234-48c8-bb82-cc8276f86716 # Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a17c419-bd38-4baf-9436-c521466d442b # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6e47063-6662-420b-8f08-084b7c1523b6 # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6a17c419-bd38-4baf-9436-c521466d442b: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  32aa8ee0-7612-4171-890d-39e6eca303f3: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  31937085-7234-48c8-bb82-cc8276f86716: # Number
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: number
    instructions: ''
    name: Number
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c6e47063-6662-420b-8f08-084b7c1523b6: # Background Color
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: backgroundColor
    instructions: ''
    name: 'Background Color'
    searchable: false
    settings:
      defaultColor: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
handle: statistic
name: Statistic
sortOrder: 1
