fieldLayouts:
  a79723cd-77fa-4cb4-aaa7-0f71912123af:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: 'Page Data'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Content'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 70b04be1-ca61-4f64-8983-47f37be11675 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7cec95cc-1712-4f28-b46f-812763ed6230 # Page URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 30d7b80d-5ede-47a8-8b53-9a193547c750 # Page Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b395b4bc-4cdd-4edf-a06c-5c3ed9e758cb # Page Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: ba9a3316-329c-4df5-8ddd-9abc7ac9f7d7 # Page Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: 'Page SEO'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: d5c3224c-f766-4625-ac73-882d233e1ff0 # Is External URL?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 40816dba-f57f-46d5-92bb-b0be3bd8ffc0 # External URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: fb84bf1a-5324-4c6b-998c-a9fc6d5d1134 # Hide from Navigation?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 6e7cdd12-5e29-4b9e-9527-e21c05429c77 # Is Page Link Disabled?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: 'Page Settings'
        sortOrder: 4
handle: default
hasTitleField: true
name: Default
section: dc4c72fc-fc7a-4701-ab4e-1a141165f786 # Public Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
