columnSuffix: null
contentColumnType: string
fieldGroup: f1a14336-6b77-4ebd-89e6-e50a5bb55776 # Globals - Site Footer
handle: footerButtons
instructions: ''
name: 'Footer Buttons'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 8ff7c066-e648-4ff8-bb27-30e5b1252556 # Destination
        -
          __assoc__:
            -
              - width
              - ''
      -
        - ed1a23e8-8e96-42c3-9a48-7709c6bcf656 # Store Image
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_footerbuttons}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
