columnSuffix: null
contentColumnType: string
fieldGroup: c4a8b2e0-0c74-4df4-9c1a-15763cf310d0 # Common - Form Picture
handle: formChar1
instructions: ''
name: 'Form Char1'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
