columnSuffix: null
contentColumnType: string
fieldGroup: 574b4144-8924-4889-ac4d-eab24ab39def # Common - Page Header
handle: icons
instructions: ''
name: Icons
searchable: false
settings:
  contentTable: '{{%stc_icons}}'
  fieldLayout: table
  maxRows: '3'
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
