columnSuffix: qcyqlues
contentColumnType: boolean
fieldGroup: 1d2fca35-7d0e-4f92-a63e-d4eb52da96fb # Common - Page Data
handle: isExternalUrl
instructions: "Select if you want this page to be external URL.\r\nRemember to enter external URL in order for this to work."
name: 'Is External URL?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
