columnSuffix: wygjgbav
contentColumnType: boolean
fieldGroup: 1d2fca35-7d0e-4f92-a63e-d4eb52da96fb # Common - Page Data
handle: isPageDisabled
instructions: 'Should page link be disabled?'
name: 'Is Page Link Disabled?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
