columnSuffix: null
contentColumnType: string
fieldGroup: 574b4144-8924-4889-ac4d-eab24ab39def # Common - Page Header
handle: phoneImage
instructions: ''
name: 'Phone Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
