columnSuffix: bvcskhaf
contentColumnType: text
fieldGroup: c4e164b5-66b6-4259-9985-d28e3cceae21 # Globals - Site Settings
handle: siteGoogleUaTrackingCode
instructions: "Add UA tracking code.\r\nNOTE: If you add UA tracking code, remove GTM tracking code. Only 1 should be enabled on website."
name: 'Site Google UA Tracking Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
