field: 85b0f58d-b253-4081-90fa-01c6d3d49ff7 # Nav Button
fieldLayouts:
  566d18c0-9f67-468f-8e10-e457e82495ee:
    tabs:
      -
        elements:
          -
            fieldUid: 37c56a7f-ffe8-45c5-a4eb-bfb88f53a99b # Destination
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d36b5a0b-069a-4df6-82af-acecb76dfe44 # Button Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  37c56a7f-ffe8-45c5-a4eb-bfb88f53a99b: # Destination
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: destination
    instructions: ''
    name: Destination
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  d36b5a0b-069a-4df6-82af-acecb76dfe44: # Button Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
