field: c694933e-c41c-4948-af64-4226c2b14db4 # Store
fieldLayouts:
  b7332419-d3cb-4dbe-9183-ba48e50b004b:
    tabs:
      -
        elements:
          -
            fieldUid: cdb48d73-ede4-4a4a-acc6-d52866a64cd5 # Store Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9b945315-3db4-41ba-9110-8332d8eb81ab # Destination
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9b945315-3db4-41ba-9110-8332d8eb81ab: # Destination
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: destination
    instructions: ''
    name: Destination
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  cdb48d73-ede4-4a4a-acc6-d52866a64cd5: # Store Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: storeImage
    instructions: ''
    name: 'Store Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
