defaultPlacement: end
enableVersioning: false
handle: publicPages
name: 'Public Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  27aff492-2400-42d9-878a-bd134e93ebd6: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: page/public
    uriFormat: '{slug}'
structure:
  maxLevels: 2
  uid: cfe17d4c-272e-45a8-969e-e29d2c116390
type: structure
